language: java
services:
- docker
script:
- docker build -t lusid-sdk-java-test .
- docker run -e FBN_TOKEN_URL=$FBN_TOKEN_URL -e FBN_USERNAME=$FBN_USERNAME -e FBN_PASSWORD=$FBN_PASSWORD
  -e FBN_CLIENT_ID=$FBN_CLIENT_ID -e FBN_CLIENT_SECRET=$FBN_CLIENT_SECRET -e FBN_LUSID_API_URL=$FBN_LUSID_API_URL
  -v $(pwd):/usr/src/ lusid-sdk-java-test
notifications:
  slack:
    rooms:
      secure: "rERaOGUUZmADbdxNIZOaOfRqqebqK2IcyohJKsBVi8t3JtpQHKmsFJs3sSx9mpx9xqQKXvuYmWpR9BW0HiZt+bPUFxvlzTKMQqqy4t77+UfsMwBDG+7/ME9jGiZazTtmJiAvc+dNB0iNSaB50dh2DAalbqUtgJVjkgYf2Riu6KLmbM2S0sjf6C9Qv4svFeJXX1Yaa4X4SuhTXemlkassUvSggxwu7YzXsXjnL4L5NBwtM49ULRLbfyVLkk/iggfqk9QmwutOfcHxO6QxJEQ9ce3DNkukz9LiMv1sdINIE+7xhwGEp7yGCBm3G9siUAG/JLmU2E9lM0pFhnA6qcFKABRFrYQC652MY4mP7l7QJCuDrm6XP+teX+u4LrpsmFjE+hDwglYCii5//pVhoHgrO2uoie5VOSTDBAiyl2tyX8jQ03vU/NdAbFrTWTofYUPlcyR9wuH15g1mKzON2TIo4Zp95L7iLxSIYCejVil4aD+MG0wKv2R/WHDqXOBjXFDruUqw497WzYQ+aNU8nn0WTMDEiq9LHzfrIm/I1GuhWQvS9IM/5yYC6CfjuMCxmgmhQeHZYkXC2q35wtpxe0BVLqQYluwJaRQ8JoSjZyj0E/Y+boEm2A4aQShi/Df8Us8OkYDEUFbYmZjUaJxxEsgxAMcXd7n74qdWaQEOe4mynCM="
    on_failure: always
